'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.8794
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Cabañas.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property BotonAceptarMaderaBlanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonAceptarMaderaBlanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonAceptarMaderaNegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonAceptarMaderaNegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonActualizarMaderaBlanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonActualizarMaderaBlanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonActualizarMaderaNegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonActualizarMaderaNegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonAgregarMaderaBlanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonAgregarMaderaBlanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonAgregarMaderaBlancoFrm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonAgregarMaderaBlancoFrm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonAgregarMaderaNegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonAgregarMaderaNegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonAgregarMaderaNegroFrm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonAgregarMaderaNegroFrm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonBuscarMaderaBlanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonBuscarMaderaBlanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonBuscarMaderaNegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonBuscarMaderaNegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonCancelarMaderaBlanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonCancelarMaderaBlanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonCancelarMaderaNegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonCancelarMaderaNegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property botoncancreservablanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botoncancreservablanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property botoncancreservanegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botoncancreservanegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonCerrar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonCerrar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonCerrar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonCerrar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonCerrarMaderaBlanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonCerrarMaderaBlanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonCerrarMaderaNegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonCerrarMaderaNegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonConsultarCostosMaderaBlanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonConsultarCostosMaderaBlanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonConsultarCostosMaderaNegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonConsultarCostosMaderaNegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonDetalleCancelacionMaderaBlanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonDetalleCancelacionMaderaBlanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonDetalleCancelacionMaderaNegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonDetalleCancelacionMaderaNegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonEleiminarMaderaBlanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonEleiminarMaderaBlanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonEliminarMaderaBlancoFrm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonEliminarMaderaBlancoFrm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonEliminarMaderaNegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonEliminarMaderaNegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonEliminarMaderaNegroFrm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonEliminarMaderaNegroFrm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonModificarMaderaBlanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonModificarMaderaBlanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonModificarMaderaNegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonModificarMaderaNegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonNuevaReservaMaderaBlanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonNuevaReservaMaderaBlanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonNuevaReservaMaderaNegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonNuevaReservaMaderaNegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonPagosMaderaBlanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonPagosMaderaBlanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BotonPagosMaderaNegro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BotonPagosMaderaNegro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FondoMaderaClaro3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoMaderaClaro3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FondoMaderaPanel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoMaderaPanel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icono_calendario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icono_calendario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IconoCabania() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoCabania", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IconoCabaniaSombra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoCabaniaSombra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IconoCalendario2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoCalendario2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IconoCalendarioSombra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoCalendarioSombra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IconoHuesped() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoHuesped", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IconoHuespedSombra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoHuespedSombra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IconoHuespedSombra2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoHuespedSombra2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
